{
 "title": "Grafana Monitoring",
 "tags": [
  "staging",
  "grafana"
 ],
 "refresh": "10s",
 "panels": [
  {
   "title": "Datasources",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "targets": [
    { "expr": "grafana_datasources" }
   ]
  },
  {
   "title": "Active Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "targets": [
    { "expr": "grafana_stat_total_users" }
   ]
  },
  {
   "title": "Total Dashboards",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "targets": [
    { "expr": "grafana_stat_total_dashboards" }
   ]
  },
  {
   "title": "Total Panels",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "targets": [
    { "expr": "grafana_stat_total_panels" }
   ]
  }
 ]
}